sensor_msgs/Image image # Original image to detect faces in
---
int16 number # Number of faces detected
float32 use_time # Time taken to detect faces in seconds
int32[] top # The position of faces in image
int32[] right
int32[] bottom
int32[] left